site_name: "IA - 2022.1"

theme:
  name: material
  favicon: assets/logo/ia.png
  logo: assets/logo/ia.png

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Sobre: index.md
  - Introdução à IA:
      - Impressão Geral: portfolio_01/impressao_geral.md
      - Conceitos: portfolio_01/conceitos.md
      - Materiais extras: portfolio_01/discussoes.md
      - Apresentação de Problemas: portfolio_01/problemas.md
      - Conclusão: portfolio_01/conclusao.md
  - Agentes e Ambientes:
      - Impressão Geral: portfolio_02/impressao_geral.md
      - Conceitos: portfolio_02/conceitos.md
      - Materiais extras: portfolio_02/discussoes.md
      - Apresentação de Problemas: portfolio_02/problemas.md
      - Conclusão: portfolio_02/conclusao.md
  - Algoritmos de busca:
      - Impressão Geral: portfolio_03/impressao_geral.md
      - Conceitos: portfolio_03/conceitos.md
      - Materiais extras: portfolio_03/discussoes.md
      - Apresentação de Problemas: portfolio_03/problemas.md
      - Conclusão: portfolio_03/conclusao.md
  - Problemas de Satisfação de Condições:
      - Impressão Geral: portfolio_04/impressao_geral.md
      - Conceitos: portfolio_04/conceitos.md
      - Materiais extras: portfolio_04/discussoes.md
      - Apresentação de Problemas: portfolio_04/problemas.md
      - Conclusão: portfolio_04/conclusao.md
